# Generated by Django 4.0.3 on 2022-03-17 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_id', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='geo_id.geolocation')),
            ],
        ),
    ]
